# Generated by Django 5.2.5 on 2025-09-05 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('phone', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
            ],
            options={
                'db_table': 'employers',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('phone', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=500)),
                ('is_available', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
            ],
            options={
                'db_table': 'workers',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('work_date', models.DateField()),
                ('wage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('detail', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'open'), ('assigned', 'assigned'), ('completed', 'completed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employer_phone', models.ForeignKey(db_column='employer_phone', on_delete=django.db.models.deletion.CASCADE, to='api.employer')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='JobContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacted_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.CharField(blank=True, choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('no_response', 'no_response')], max_length=20, null=True)),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='api.job')),
                ('worker_phone', models.ForeignKey(db_column='worker_phone', on_delete=django.db.models.deletion.CASCADE, to='api.worker')),
            ],
            options={
                'db_table': 'job_contacts',
                'unique_together': {('job', 'worker_phone')},
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_accept', models.BooleanField(default=False)),
                ('employer_accept', models.BooleanField(default=False)),
                ('worker_complete', models.BooleanField(default=False)),
                ('employer_complete', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('declined', 'declined'), ('completed', 'completed')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.job')),
                ('worker_phone', models.ForeignKey(db_column='worker_phone', on_delete=django.db.models.deletion.CASCADE, to='api.worker')),
            ],
            options={
                'db_table': 'job_applications',
                'unique_together': {('job', 'worker_phone')},
            },
        ),
    ]
