# Generated by Django 5.2.5 on 2025-09-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('waiting_for_worker_confirmation', 'waiting_for_worker_confirmation'), ('accepted', 'accepted'), ('declined', 'declined'), ('completed', 'completed')], default='pending', max_length=40),
        ),
    ]
