# Generated by Django 5.2.5 on 2025-09-07 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_jobapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer_response', models.BooleanField(default=None, null=True)),
                ('worker_response', models.BooleanField(default=None, null=True)),
                ('employer_complete', models.BooleanField(default=False)),
                ('worker_complete', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('declined', 'declined'), ('completed', 'completed')], default='pending', max_length=20)),
                ('employer_phone', models.ForeignKey(db_column='employer_phone', on_delete=django.db.models.deletion.CASCADE, to='api.employer')),
                ('worker_phone', models.ForeignKey(db_column='worker_phone', on_delete=django.db.models.deletion.CASCADE, to='api.worker')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
