# Generated by Django 5.2.5 on 2025-09-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='latitude',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='longitude',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='has_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='latitude',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='longitude',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='wages',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
